project:
  type: website

website:
  title: "Travel Log"
  navbar:
    left:
      - about.qmd
      - logs/logs.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: source
