---
title: "Birding Double Day Trip 12th-13th Feb 2021"
date: 2021-02-12
country: Czechia
authors: Honza Grünwald
---

*This document was originally created by [Honza Grünwald](https://ebird.org/profile/OTIwMTgz/world). I have just collated it into my collection of travel planning logs.*

# 12th February, Sunset 17:14

**1030 meeting at the Central Station Prague**

**1100-1300 Vltava river (Prague centre)**

Certain: Mew Gull

Possible: Herring Gull, Greater Scaup, Peregrine Falcon

**1330-1335 Malešická spalovna (Prague)**

Possibe: Peregrine Falcon

**1350-1420 Slatina pond (Prague)**

Possible: Jack Snipe, Bearded Reedling, Common Redpoll

**1440-1500 Vyšehořovice (field)**

Possible: Crested Lark, Peregrine Falcon, Rough-Legged Buzzard, Northern Goshawk, Corn Bunting

**1545-1715 Křičeň-Staré Ždánice-Oplatil (fields and lakes)**

Possible: Wood Lark, Snow Bunting, Tundra Swan, Rough-Legged Buzzard, Norhtern Goshawk, Hen Harrier – in the fields; Arctic Loon, Greater Scaup, Velvet Scoter, Tundra Bean Goose – on water.

# 13th February, Sunrise 7:15, Sunset 17:16

**0515 Wake up!!!**

**0545 Departure**

**0715-0945 Nechranice (reservoir)**

Possible: Arctic Loon, Red-throated Loon, Tundra Bean Goose, Red-breasted Merganster, Greater Scaup, Velvet Scoter, Horned Grebe, Mew Gull, Herring Gull, Water Pipit, Corn Bunting, Common Redpoll, Wood Lark, Merlin, Northern Goshawk, Greater Black-backed Gull

**1015-1100 Kyjice / Zaječice (reservoir)**

Possible: Arctic Loon, Red-throated Loon, Tundra Bean Goose, Red-breasted Merganster, Greater Scaup, Velvet Scoter, Horned Grebe, Mew Gull, Herring Gull, Water Pipit, Corn Bunting, Common Redpoll, Wood Lark, Merlin, Northern Goshawk

**1130-1430 Most (reservoir)**

Possible: Arctic Loon, Red-throated Loon, Tundra Bean Goose, Red-breasted Merganster, Greater Scaup, Velvet Scoter, Horned Grebe, Mew Gull, Herring Gull, Water Pipit, Corn Bunting, Common Redpoll, Wood Lark, Merlin, Northern Goshawk, Greater Black-backed Gull, Great Bittern, Bearded Reedling, Hen Harrier

**1500-1600 Lenešice (fields, pond)**

Possible: Whooper Swan
